### ISSUE TITLE
Low scores on PageSpeed

### ISSUE THREAD

**Issue by dannycjones** [HackSheffield/2016f.hacksheffield.co#14]
[PageSpeed Ranking](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.hacksheffield.co%2F)

62/100 Mobile
76/100 Desktop

**Comment by dannycjones** [comment]
Well this website will be deleted soon.

**Comment by jacobwalkr** [comment]
76/100 is a first
