### ISSUE TITLE
Non- .sheffield.ac.uk domains point to GitHub, not VM

### ISSUE THREAD

**Issue by dannycjones** [HackSheffield/2016f.hacksheffield.co#49]

**Comment by robjtede** [comment]
Where are DNS records held?

**Comment by dannycjones** [comment]
It's currently on my personal CloudFlare account.

**Comment by robjtede** [comment]
So lets get an account on the society email and transfer things?

**Comment by robjtede** [comment]
Just came to look at things and noticed this, again.
